spring:
  application:
    name: accounts-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.event.merge.entity_copy_observer: allow
    datasource:
     url: jdbc:mysql://98.82.183.74:3307/DMH-DB?createDatabaseIfNotExist=true&serverTimezone=UTC
     username: root
     password: admin
     driver-class-name: com.mysql.cj.jdbc.Driver
    
management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true
info:
  app:
    name: accounts-service
    description: microservicio de cuentas de clientes desde github
    version: 1.0.0

eureka:
  instance:
    hostname: localhost
    statusPageUrlPath: http://98.82.183.74:8085/actuator/info
    healthCheckUrlPath: http://98.82.183.74:8085/actuator/health
  client:
    serviceUrl:
      defaultZone: http://98.82.183.74:8761/eureka/

server:
  port: 8085

jwt:
  secret: mySecretKey12345
