spring:
  application:
    name: users-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.event.merge.entity_copy_observer: allow
    datasource:
      url: jdbc:mysql://mysql:3306/DMH-DB?createDatabaseIfNotExist=true&serverTimezone=UTC
      username: admin
      password: admin
      driverClassName: com.mysql.cj.jdbc.Driver
management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: true
info:
  app:
    name: users-service
    description: microservicio de registro y login desde config server github
    version: 1.0.0

eureka:
  instance:
    hostname: localhost
    statusPageUrlPath: http://localhost:8081/actuator/info
    healthCheckUrlPath: http://localhost:8081/actuator/health
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

server:
  port: 8081
