spring:
  application:
    name: users-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.event.merge.entity_copy_observer: allow
    datasource:
     url: jdbc:mysql://mysql:3307/DMH-DB?createDatabaseIfNotExist=true&serverTimezone=UTC
     username: root
     password: admin
     driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true

info:
  app:
    name: users-service
    description: Microservicio de registro y login desde config server GitHub
    version: 1.0.0

eureka:
  instance:
    hostname: localhost
    status-page-url: http://localhost:8082/actuator/info
    health-check-url: http://localhost:8082/actuator/health
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8082
